pipeline:
  test:
    image: node:alpine
    commands:
      - echo hi electron-tutorial app
      - ehco ${GITHUB_TOKEN}
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run package-linux
  publish:
    github_release:
      image: plugins/github-release
      api_key: ${GITHUB_TOKEN}
      files:
        - release-builds/*
      checksum: sha256
