pipeline:
  test:
    image: node:alpine
    commands:
      - echo hi electron-tutorial app
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run package-linux
  github_release:
    image: plugins/drone-github-release
    api_key: $github_token
    files: release-builds/*
    checksum: sha256
